# Development version - dengan hot reload dan debug features
services:
  tradebot-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tradebot-dev
    restart: "no"  # Don't auto-restart in development
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    privileged: true
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
      - ./vpn/config.ovpn:/app/vpn/config.ovpn:ro
      # Mount source code for hot reload (development only)
      - .:/app
    environment:
      - TZ=Asia/Jakarta
      - VPN_USERNAME=${VPN_USERNAME:-}
      - VPN_PASSWORD=${VPN_PASSWORD:-}
      - VPN_ENABLED=${VPN_ENABLED:-false}  # Disable VPN by default in dev
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    ports:
      - "9876:8080"
      - "5678:5678"  # Debug port for VS Code
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # Override CMD for development (optional)
    # command: ["python", "-u", "main.py"]
